services:
  mongodb:
    image: mongodb/7.0-jammy
    hostname: mongodb
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27007:27017
    volumes:
      - mongodb:/data/mongot

