services:
  mongodb:
    image: mongo:7-jammy

    container_name: mongodb

    ports:
      - 27007:27017

    volumes:
      - mongodata:/data/db

    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      
    restart: always

  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

    restart: always

networks: 
  backend:

volumes:
  mongodata:
  pgvector_data: