global:
  scrape_interval: 15s
  evalutation_interval: 15s

scrape_configs:

  - job_name: "qdrant"
    static_configs:
      - targets: ["qdrant:6333"]
    metrics_path: "/metrics"

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]